### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lhermann** [lhermann/langify-docs#12]
# These are our Todo's for langify:

- [ ] User Profile / User Settings
- [ ] Restore older versions of a translation
- [ ] Realtime Collaboration (right now, changes are only updated every 5 sec)
- [ ] User Permissions coupled with a Reputation System (earn trust and get more permissions) [[details](https://github.com/lhermann/langify-docs/blob/privileges/authorization.md)]
- [ ] Quality Assurance of translations [[details](https://github.com/lhermann/langify-docs/blob/master/quality_assurance.md)]
- [ ] Approvals/Disapprovals for contributions to translations 
- [ ] Ellen White Estate Glossary (highlight and explain particular words)
- [ ] Thesaurus (see synonyms and alternative translations of words in popup)
